repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.12.0
    hooks:
      - id: black
        language_version: python3.13
        args: [ "--line-length=100" ]
  - repo: https://github.com/pycqa/isort
    rev: 7.0.0
    hooks:
      - id: isort
  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        args: [ --max-line-length=100, --extend-ignore=E402 ]
  - repo: https://github.com/semgrep/semgrep
    rev: v1.89.0  # Check for the latest version on GitHub
    hooks:
      - id: semgrep
        name: Semgrep (Security & Quality)
        # Configure which rulesets to use
        args: [ '--config', 'p/python', '--config', 'p/owasp-top-ten', '--error' ]
  - repo: local
    hooks:
      - id: unittest
        name: Run Unittest
        # "discover" finds all files matching the pattern
        entry: uv run python -m unittest discover -s tests -p "test*.py"
        language: system
        types: [ python ]
        pass_filenames: false
        verbose: true
